Allow overriding nginx.conf injection

diff --git a/bin/finalize b/bin/finalize
--- a/bin/finalize
+++ b/bin/finalize
@@ -59,3 +59,22 @@ echo 'export PATH=$DEPS_DIR/'"${INDEX}"'/bin$([[ ! -z "${PATH:-}" ]] && echo ":$
 
 chmod +x "$app_profile_dir"/*
 ls -al "$app_profile_dir"
+
+# Add lua_ssl_trusted_certificate to nginx.conf.
+# We can't do this in the `supply` phase because it would confuse the base Nginx buildpack:
+# when it tries to check the configuration the ca-certs.pem file hasn't been created yet
+# so would fail.
+if [[ "$ODB_SKIP_LUA_SSL" == false ]]; then
+  echo ' -> Skip adding lua_ssl_trusted_certificate to nginx.conf' >&2
+else
+    nginx_conf=$(find "$BUILD_DIR" -name nginx.conf -print -quit)
+    if [[ $nginx_conf == "" ]]; then
+    echo 'WARNING: could not add lua_ssl_trusted_certificate to your nginx.conf. You might need to set it yourself.' >&2
+    else
+    echo " -> Adding lua_ssl_trusted_certificate to nginx.conf"
+    awk '/http \{/{print;print "  lua_ssl_trusted_certificate \"/home/vcap/app/ca-certs.pem\";";next}1' "$nginx_conf" > /tmp/conf
+
+    mv "$nginx_conf" "$nginx_conf".1
+    mv /tmp/conf "$nginx_conf"
+    fi
+fi
diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -92,18 +92,22 @@ sed -i 's#^prefix=.*$#prefix='"$my_deps"/nginx/luajit'#' "$my_deps"/nginx/luajit
 
 # Set the lua_package_path and lua_package_cpath in the application's nginx conf file, http section.
 # This is ridiculous. There has to be a better way
-nginx_conf=$(find "$BUILD_DIR" -name nginx.conf -print -quit)
-if [[ $nginx_conf == "" ]]; then
-  echo 'WARNING: could not add lua_package_path to your nginx.conf. Make sure you add it yourself.' >&2
+if [[ "$ODB_SKIP_LUA_PATHS" == false ]]; then
+  echo ' -> Skip adding lua_package_path and lua_package_cpath to nginx.conf' >&2
 else
-  echo " -> Adding lua_package_path to nginx.conf"
-  awk '/http \{/{print;print "  lua_package_path \"/home/vcap/deps/'"${INDEX}"'/nginx/lualib/?.lua;;\";";next}1' "$nginx_conf" > /tmp/conf.0
+  nginx_conf=$(find "$BUILD_DIR" -name nginx.conf -print -quit)
+  if [[ $nginx_conf == "" ]]; then
+    echo 'WARNING: could not add lua_package_path to your nginx.conf. Make sure you add it yourself.' >&2
+  else
+    echo " -> Adding lua_package_path to nginx.conf"
+    awk '/http \{/{print;print "  lua_package_path \"/home/vcap/deps/'"${INDEX}"'/nginx/lualib/?.lua;;\";";next}1' "$nginx_conf" > /tmp/conf.0
 
-  echo " -> Adding lua_package_cpath to nginx.conf"
-  awk '/http \{/{print;print "  lua_package_cpath \"/home/vcap/deps/'"${INDEX}"'/nginx/lualib/?.so;;\";";next}1' /tmp/conf.0 > /tmp/conf.1
+    echo " -> Adding lua_package_cpath to nginx.conf"
+    awk '/http \{/{print;print "  lua_package_cpath \"/home/vcap/deps/'"${INDEX}"'/nginx/lualib/?.so;;\";";next}1' /tmp/conf.0 > /tmp/conf.1
 
-  mv "$nginx_conf" "$nginx_conf".0
-  mv /tmp/conf.1 "$nginx_conf"
+    mv "$nginx_conf" "$nginx_conf".0
+    mv /tmp/conf.1 "$nginx_conf"
+  fi
 fi
 
 # Install the modules into nginx's deps folder.
