attempt improvements

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -24,10 +24,11 @@
 # 
 # The cache directories provided to the supply scripts of non-final buildpacks are cleared
 # if those buildpacks are upgraded or otherwise change.
-#shellcheck disable=SC2006,SC2155
+#shellcheck disable=SC2006,SC2016,SC2155
 
 echo "bin/supply running"
 
+BUILDPACK_NAME=openresty-decorator
 BIN_DIR=$(cd $(dirname $0); pwd)
 #ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
@@ -35,73 +36,57 @@ BUILD_DIR=$1
 DEPS_DIR=$3
 INDEX=$4
 
-set -x
+set -xuo
 
-# echo "BUILD_DIR: $BUILD_DIR"
-# ls -al "$BUILD_DIR"
+my_deps=$(realpath "$DEPS_DIR/$INDEX")
 
 deps_file="$BUILD_DIR"/opm.deps
-if ! [ -f "$deps_file" ] ; then
-  cat <<EOL
-WARNING: no `opm.deps` file was present in your app. Nothing to do.
-EOL
-  exit 0
-fi
+[ -f "$deps_file" ] || echo 'WARNING: no `opm.deps` file was present in your app. Did you forget something?' >&2
 
 echo "DEPS_DIR: $DEPS_DIR"
 ls -al "$DEPS_DIR"
 
-echo "DEPS_DIR/index: ${DEPS_DIR}/${INDEX}"
-ls -al "${DEPS_DIR}/${INDEX}"
+echo "my_deps: ${my_deps}"
+ls -al "$my_deps"
 
 # Find where the Nginx buildpack was installed in DEPS_DIR
-nginx_deps_dir=$(find "$DEPS_DIR" -type d -name nginx -print -quit)
-if [[ "$nginx_deps_dir" == "" ]]; then
-  cat <<EOL
-Could not find `nginx` folder in DEPS_DIR. Ensure your app was pushed with the nginx buildpack
-and that it precedes openresty-decorator-buildpack in the `buildpacks` list.
-EOL
+nginx_deps_dir=$(find "$DEPS_DIR" -type d -name nginx -print -quit)/..
+if [[ "$nginx_deps_dir" == "/.." ]]; then
+  echo "Could not find nginx. Ensure that your app was pushed with the nginx buildpack and that it \
+    precedes openresty-decorator-buildpack in the `buildpacks` list." >&2
   exit 1
+else
+  nginx_deps_dir=$(realpath "$nginx_deps_dir") # make into an absolute path
 fi
 
-# Add nginx/resty binaries to PATH
-nginx_deps_dir=$(realpath "$nginx_deps_dir")
+# Copy the entire folder from nginx's deps directory to ours, we're basically stealing it all
+cp -rT "$nginx_deps_dir" "$my_deps"
+
+ls -al "$my_deps"
+
+# hack paths within profile.d to point to our dep dir, not nginx's
+sed -i "s#\$DEPS_DIR/[0-9]#\$DEPS_DIR/${INDEX}#g" "${my_deps}/profile.d"/*
+
+# overwrite config.yml with our own buildpack name so we're not claiming to be "nginx"
+sed -i s/nginx/${BUILDPACK_NAME}/ "${my_deps}/config.yml"
+
+# Add nginx binaries to PATH
 path_suffix=$([[ -n "${PATH:-}" ]] && echo ":$PATH")
-export PATH=${nginx_deps_dir}/bin:${nginx_deps_dir}/nginx/bin:${nginx_deps_dir}/luajit/bin${path_suffix}
+export PATH=${my_deps}/bin:${my_deps}/nginx/bin:${my_deps}/nginx/luajit/bin${path_suffix}
 
 # Problem: as a side effect of the Nginx buildpack having done its work, the nginx_path in openresty's
 # config file is set to some temp folder that no longer exists:
-#
 #   my $nginx_path = '/tmp/d20190829-7-6tk6jx/openresty/nginx/sbin/nginx';
+# opm wants to keep installing into this folder. Change the path to be inside ${my_deps} so it will work
 #
-# opm wants to keep installing into that folder and it's hard to change. To work around, create the
-# folder that opm wants as a symlink to ${nginx_deps_dir}/nginx.
-#
-# NOTE: I *think* that as the final buildpack, we are permitted to modify any folder in $DEPS_DIR,
-# but the PCF docs are not clear on this point. If we're breaking the rules here, we should instead
-# copy $nginx_deps_dir into $DEPS_DIR/$INDEX, and then modify it.
-nginx_path=$(grep "my \$nginx_path =" "${nginx_deps_dir}"/bin/resty | awk '{print $4}' | tr -d \'\;)
-temp_dir=${nginx_path%/openresty/nginx/sbin/nginx} # remove suffix
-
-mkdir -p "$temp_dir"
-( cd "$temp_dir" && ln -s "$nginx_deps_dir" openresty )
+sed -i 's#^my $nginx_path =.*$#my $nginx_path = '"'${my_deps}/nginx/nginx/sbin/nginx'"';#' "$my_deps"/nginx/bin/resty
 
 # Install the modules into nginx's deps folder.
 while IFS= read -r line ; do
-    [[ $line =~ ^[[:space:]]*$ ]] && continue
+  [[ $line =~ ^[[:space:]]*$ ]] && continue
 
-    opm install "$line"
+  opm install "$line"
 done < "$deps_file"
-
-# Copy the entire folder from nginx's deps directory to ours, so we're basically stealing it all
-# TODO do this first before dumping crap into nginx's deps folder.
-cp -r "${nginx_deps_dir}/.." "${DEPS_DIR}/${INDEX}/"
-
-# hack profile.d paths to point to $DEPS_DIR/$INDEX
-sed -i "s#\$DEPS_DIR/[0-9]#\$DEPS_DIR/${INDEX}#g" "${DEPS_DIR}/${INDEX}/profile.d"/*
-
-# overrwrite config.yml with our own name
-sed -i s/nginx/openresty-decorator/ "${DEPS_DIR}/${INDEX}/config.yml"
 
 find "${DEPS_DIR}/${INDEX}/" -maxdepth 2
 
